services:
  jwt_auth_service:
    build:
      context: ./CustomJWTAuthorization
      dockerfile: Dockerfile
    image: jwt_auth_service
    ports:
      - "8001:8000"
    entrypoint: [ "/app/entrypoint.sh" ]
    command: bash -c "python -u manage.py runserver 0.0.0.0:8000"
    depends_on:
      postgres_db:
        condition: service_healthy

  postgres_db:
    container_name: jwt_service_postgres
    image: postgres:16.0-alpine
    command: -c 'max_connections=1000'
    volumes:
      - jwt_service_postgres_data:/var/lib/postgresql/jwt_service_postgres_data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 7s
      retries: 5
      timeout: 7s
    ports:
      - "5432:5432"

volumes:
  jwt_service_postgres_data: