# Generated by Django 6.0.3 on 2026-03-31 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('regular', 'Обычная'), ('special', 'Специальная')], default='regular', max_length=255)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_user_api.role')),
            ],
            options={
                'verbose_name': 'AccessRule',
                'verbose_name_plural': 'AccessRules',
                'unique_together': {('role', 'type')},
            },
        ),
    ]
